### ISSUE TITLE
Include OpenGraph tags in the result page

### ISSUE THREAD

**Issue by roipoussiere** [MieuxVoter/mvfront-react#54]
The result page could include [OpenGraph tags](https://ogp.me/), in particular `property="og:image"` set to the image url displaying the merit profile, generated by the `/merit-profile` endpoint (https://github.com/MieuxVoter/mv-api-spec/issues/10).

This will allow Facebook, LinkedIn, Slack, Twitter, WhatsApp, Telegram, Discourse, among many others services that support OpenGraph, to directly embed the merit profile image and its result, just by pasting the election result url in any post.

A *Share this* button could encourage users to do this by:
- including links to some mainstream social media with a predefined message (that include the link of the result page)
- including code samples in html and markdown to let them share in other places (ie. `![](https://api.mieuxvoter.fr/merit-profile?<...>.svg)` for markdown).

I may work on a PR for this once my merit-profile module will be finished.

**Comment by guhur** [comment]
So right now, we are kind of limited for open graph to static elements due to our architecture. 

The reason for this is that Facebook downloads only the first MB of a web page. Thus React is not entirely loaded and it can't be used to inject the poll ID/ title in the meta tags. 

We considered several solutions:
- our CDN netlify offers a pre rendering option beta, something that might solve this issue;
- switching to Gatsby to generate static pages for each poll. 

If we just want to update the image, we might try to inject just a JS snippet in the head tag. This script copies the poll ID given in the URL to the og meta. Dirty but simple. 


⁣ ​

**Comment by guhur** [comment]
This is fixed with the integration of Next Js since tag v1.1
