### ISSUE TITLE
Implementation in Chile?

### ISSUE THREAD

**Issue by fforster** [MieuxVoter/mvfront-react#7]
Dear all, we are a group of researchers at the Center for Mathematical Modeling in Chile (http://www.cmm.uchile.cl/) which is very interested in using majority judgment to help decision makers understand better the current social demands in our country. We have found this great repository and have cloned it and translated most of the text into Spanish (Lat. Am.) in a new branch. We are wondering how mature you think the current version is for us to start using it in a more massive scale and how much stress you have put into it in previous tests. Also, we would like to understand better what are all the components needed to set up this system. 
Would it be possible to set up some meeting for next week? Things are moving quite fast in Chile as you may have heard in the news. 
Thanks a lot!
Francisco

**Comment by jmaureir** [comment]
Hi Developers,

Just a complement from @fforster question. Is the code addressing the votes injection via another way different from the site interface (the browser)?  special case the votes coming from clients behind a maked IP (clients with private IPs masked with a public IP - common case, home wifi router or private corporate network). As mentioned, we are planning to deploy a MJ voting system as a pilot voting and we are wondering how usable is your code in a production level.

thanks in advance

JcM

**Comment by guhur** [comment]
Hi,
Thanks a lot for your kind interest in the project :) 

Thanks a lot for the translation as well. Could you open up a pull request with the [WIP] tag in the title (it stands for Work In Progress). 

Concerning the progress of development, we are receiving help from a group of students, that are connecting the backend (http://github.com/MieuxVoter/mv-api) to Belenios, which is a state-of-the-art electronic vote ballot system, whereas another group of students is working on a React native app for voting -- basically the app would scan a QR code and triggers a ballot. 

As for now, all of our projects are still in beta and are not ready for production, but it's not that far from there, since Belenios has been tested on large scale elections (a few thousands), whereas React, used for the UI interface, is known for scaling very well. Overall, we estimated that the app would need around 5 days of devs for being ready. 

I'd be glad to Skype you to discuss more about it. I'd be free on Wednesday or Thursday.

**Comment by guhur** [comment]
Hi when could we talk about this?

**Comment by fforster** [comment]
Hi, could we talk some day next week? For example, Thursday 2 PM your time?

**Comment by fforster** [comment]
We can coordinate via email
![Screenshot from 2019-12-27 14-24-12](https://user-images.githubusercontent.com/5090828/71526220-965b1f80-28b4-11ea-9c61-d68bd186d43b.png)
